# Streamlit Secrets Configuration
# This file will be used for local development and can be deployed to Streamlit Cloud
# For production deployment, these secrets should be added through Streamlit Cloud's secrets management

[api_keys]
HF_API_KEY = "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"
NEWSAPI_KEY = "175b3c75dd2c4ea3b204eb3308a5ddf4"  # Optional - add if you have a NewsAPI key
REDDIT_CLIENT_ID = "mfxOsAZuG-N64-UGvKn3Tw"  # Optional - add if you want Reddit integration
REDDIT_CLIENT_SECRET = "2W_qAmmFjHH-eFr9QPmetnZlYo88kQ"  # Optional - add if you want Reddit integration
LANGSMITH_API_KEY = "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"  # Optional - add for workflow monitoring
TAVILY_API_KEY="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"
FACTCHECK_API_KEY="AIzaSyA5ftz1DeIRwYKn_KD8-UAg66nM9ULLZBY"

[configuration]
# Any additional configuration can go here
debug_mode = false
